// Generated by CoffeeScript 1.3.1
(function() {

  $(function() {
    if (!window.hasOwnProperty('freshenReceive')) {
      window.freshenReceive = function(data) {
        return document.location = document.location;
      };
      return $.ajax({
        url: 'http://localhost:9020/',
        dataType: 'jsonp',
        data: {
          callback: 'window.freshenReceive'
        }
      });
    }
  });

}).call(this);
