// Generated by CoffeeScript 1.3.1
(function() {

  $(function() {
    window.freshenReceive = function(data) {
      if (parseInt(data) > 0) {
        return location.reload();
      } else {
        return $.ajax({
          url: 'http://localhost:9020/',
          dataType: 'jsonp',
          jsonp: false,
          jsonpCallback: 'window.freshenReceive',
          cache: true,
          data: {
            callback: 'window.freshenReceive'
          }
        });
      }
    };
    return window.setTimeout((function() {
      return window.freshenReceive(0);
    }), 1000);
  });

}).call(this);
